vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       artists_images:
           uri_prefix: /images/artists
           upload_destination: '%kernel.project_dir%/public/images/artists'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       link_svg:
           uri_prefix: /images/svg
           upload_destination: '%kernel.project_dir%/public/images/svg'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
